/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsReleaseSourcesRouteImport } from './routes/docs.release-sources'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsCommandsRouteImport } from './routes/docs.commands'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReleaseSourcesRoute = DocsReleaseSourcesRouteImport.update({
  id: '/release-sources',
  path: '/release-sources',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/release-sources': typeof DocsReleaseSourcesRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/release-sources': typeof DocsReleaseSourcesRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/release-sources': typeof DocsReleaseSourcesRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/installation'
    | '/docs/release-sources'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/installation'
    | '/docs/release-sources'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/installation'
    | '/docs/release-sources'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/release-sources': {
      id: '/docs/release-sources'
      path: '/release-sources'
      fullPath: '/docs/release-sources'
      preLoaderRoute: typeof DocsReleaseSourcesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsReleaseSourcesRoute: typeof DocsReleaseSourcesRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCommandsRoute: DocsCommandsRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsReleaseSourcesRoute: DocsReleaseSourcesRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
